### PR TITLE
Added credentials support to gnmi.

### LINKED ISSUE #9: gNMI should use new method of credential password modeling.
The gNMI protocol should use the new method of [credential password modeling](http://wwwin-pyats.cisco.com/documentation/latest/topology/schema.html) to allow users to hide passwords and usernames on target test devices.

### PR DESCRIPTION
**Pull request by miott**
Fixes #9 

Connection logic now looks for "credentials" in connection_info and uses it.

### CODE REVIEW

**Comment by jeaubin** [comment]
Should this require documentation changes?

**Comment by miott** [comment]
> Should this require documentation changes?

I have not added ANY documentation for the gnmi usage.  I will add another issue for that.  I am working on integrating yang.connector with the yangsuite-gnmi plugin so as soon as I get past that I will come back and document.

**Comment by miott** [comment]
BTW, the credentials are documented for Netconf and they are the same.  What I was referring to was the fact that nothing is documented for gnmi.

**Comment by jeaubin** [comment]
Sounds good,  thanks @miott

**Pull request merged**
